apiVersion: v2
name: windforlife
description: The WindForLife Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    #version: "~10.3.13"
    # update the postgresql chart to the latest version 
    version: "~16.3.0"
    condition: postgresql.poc
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    #version: "~12.8.3"
    # the lastest stable version for Redis 7.4
    version: "20.0.0"
