nameOverride: ""
fullnameOverride: ""

app:
  replicaCount: 1
  image:
    repository: windforlife
    pullPolicy: IfNotPresent
    tag: "1.0.0"
  imagePullSecrets: []
  # We want to inject env vars in our container app.
  env:
    MY_NEEDED_ENV_VAR: 14
    MY_OTHER_NEEDED_ENV_VAR: "development"
  serviceAccount:
    create: true
    name: ""
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  resources:
    limits:
      cpu: 5m
      memory: 16Mi
    requests:
      cpu: 2m
      memory: 8Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

postgresql:
  postgresqlUsername: "postgres"
  postgresqlPassword: "postgressecret"
  postgresqlDatabase: "mydatabase"

redis:
  password: "mysupersecretredispassword"
