apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-app
type: Opaque
data:
  # add base54 encode
  redis-password: {{ .Values.redis.password | b64enc | quote }}


#add another secret for postgresql's secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-app
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresqlPassword | b64enc | quote }}
  postgres-username: {{ .Values.postgresql.auth.postgresqlUsername | b64enc | quote }}


